version: '3.8'

services:
  db:
    build: docker/mysql
    container_name: db
    volumes:
      - data-volume:/var/lib/mysql
    restart: always
    ports:
      - ":3306"
    env_file:
      - ./deliveryapp/.ENV
    healthcheck:
      test: "exit 0"
    networks:
      - live

  web:
    build: 
      context: deliveryapp/
    container_name: web
    restart: on-failure:10 
    volumes:
      - static-data:/vol/web
    expose:
      - '8000'
    env_file:
      - ./deliveryapp/.ENV
    depends_on:
      - db
    networks:
      - live

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - static-data:/vol/static
      - ./docker/myconfig:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - live


  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - live

  celery:
    build: 
      context: deliveryapp/
    command: celery -A deliveryapp worker -l info --pool=solo
    depends_on:
      - redis
      - web
    networks:
      - live

volumes:
  data-volume: {}
  static-data: {}

networks:
  live:
    driver: bridge